In [29]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [30]:
start =pd.read_csv('kidney_disease.csv')
start=start.iloc[:,1:]
start.drop('age',axis=1,inplace=True)
start.drop('wc',axis=1,inplace=True)
start.drop('pcv',axis=1,inplace=True)
start.drop('rc',axis=1,inplace=True)
start.drop('su',axis=1,inplace=True)
start.drop('rbc',axis=1,inplace=True)
start.drop('pc',axis=1,inplace=True)
start.drop('sc',axis=1,inplace=True)
start.drop('pot',axis=1,inplace=True)
start.drop('dm',axis=1,inplace=True)
start.drop('cad',axis=1,inplace=True)
start.drop('pe',axis=1,inplace=True)
start

bp     sg   al         pcc          ba    bgr    bu    sod  hemo  htn  \
0    80.0  1.020  1.0  notpresent  notpresent  121.0  36.0    NaN  15.4  yes   
1    50.0  1.020  4.0  notpresent  notpresent    NaN  18.0    NaN  11.3   no   
2    80.0  1.010  2.0  notpresent  notpresent  423.0  53.0    NaN   9.6   no   
3    70.0  1.005  4.0     present  notpresent  117.0  56.0  111.0  11.2  yes   
4    80.0  1.010  2.0  notpresent  notpresent  106.0  26.0    NaN  11.6   no   
..    ...    ...  ...         ...         ...    ...   ...    ...   ...  ...   
395  80.0  1.020  0.0  notpresent  notpresent  140.0  49.0  150.0  15.7   no   
396  70.0  1.025  0.0  notpresent  notpresent   75.0  31.0  141.0  16.5   no   
397  80.0  1.020  0.0  notpresent  notpresent  100.0  26.0  137.0  15.8   no   
398  60.0  1.025  0.0  notpresent  notpresent  114.0  50.0  135.0  14.2   no   
399  80.0  1.025  0.0  notpresent  notpresent  131.0  18.0  141.0  15.8   no   

    appet  ane classification  
0    good   no            ckd  
1    good   no            ckd  
2    poor  yes            ckd  
3    poor  yes            ckd  
4    good   no            ckd  
..    ...  ...            ...  
395  good   no         notckd  
396  good   no         notckd  
397  good   no         notckd  
398  good   no         notckd  
399  good   no         notckd  

[400 rows x 13 columns]

In [31]:
start.isnull().any()

bp                 True
sg                 True
al                 True
pcc                True
ba                 True
bgr                True
bu                 True
sod                True
hemo               True
htn                True
appet              True
ane                True
classification    False
dtype: bool

In [32]:
start['bp'].fillna((start['bp'].mean()),inplace=True)
start['sg'].fillna((start['sg'].mean()),inplace=True)
start['al'].fillna((start['al'].mean()),inplace=True)
start['bgr'].fillna((start['bgr'].mean()),inplace=True)
start['bu'].fillna((start['bu'].mean()),inplace=True)
start['sod'].fillna((start['sod'].mean()),inplace=True)
start['hemo'].fillna((start['hemo'].mean()),inplace=True)

In [33]:
start['htn']=start['htn'].fillna(value=start['htn'].mode().iloc[0])
start['ba']=start['ba'].fillna(value=start['ba'].mode().iloc[0])
start['pcc']=start['pcc'].fillna(value=start['pcc'].mode().iloc[0])
start['appet']=start['appet'].fillna(value=start['appet'].mode().iloc[0])
start['ane']=start['ane'].fillna(value=start['ane'].mode().iloc[0])

In [34]:
start.isnull().any()

bp                False
sg                False
al                False
pcc               False
ba                False
bgr               False
bu                False
sod               False
hemo              False
htn               False
appet             False
ane               False
classification    False
dtype: bool

In [35]:
from sklearn.preprocessing import LabelEncoder
lb=LabelEncoder()

In [36]:
start['pcc']=lb.fit_transform(start['pcc'])
start['ba']=lb.fit_transform(start['ba'])
start['htn']=lb.fit_transform(start['htn'])
start['appet']=lb.fit_transform(start['appet'])
start['ane']=lb.fit_transform(start['ane'])
start['classification']=lb.fit_transform(start['classification'])

In [37]:
start

bp     sg   al  pcc  ba         bgr    bu         sod  hemo  htn  \
0    80.0  1.020  1.0    0   0  121.000000  36.0  137.528754  15.4    1   
1    50.0  1.020  4.0    0   0  148.036517  18.0  137.528754  11.3    0   
2    80.0  1.010  2.0    0   0  423.000000  53.0  137.528754   9.6    0   
3    70.0  1.005  4.0    1   0  117.000000  56.0  111.000000  11.2    1   
4    80.0  1.010  2.0    0   0  106.000000  26.0  137.528754  11.6    0   
..    ...    ...  ...  ...  ..         ...   ...         ...   ...  ...   
395  80.0  1.020  0.0    0   0  140.000000  49.0  150.000000  15.7    0   
396  70.0  1.025  0.0    0   0   75.000000  31.0  141.000000  16.5    0   
397  80.0  1.020  0.0    0   0  100.000000  26.0  137.000000  15.8    0   
398  60.0  1.025  0.0    0   0  114.000000  50.0  135.000000  14.2    0   
399  80.0  1.025  0.0    0   0  131.000000  18.0  141.000000  15.8    0   

     appet  ane  classification  
0        0    0               0  
1        0    0               0  
2        1    1               0  
3        1    1               0  
4        0    0               0  
..     ...  ...             ...  
395      0    0               2  
396      0    0               2  
397      0    0               2  
398      0    0               2  
399      0    0               2  

[400 rows x 13 columns]

In [38]:
x=start.iloc[:,0:12].values
y=start.iloc[:,12:].values
x

array([[80.   ,  1.02 ,  1.   , ...,  1.   ,  0.   ,  0.   ],
       [50.   ,  1.02 ,  4.   , ...,  0.   ,  0.   ,  0.   ],
       [80.   ,  1.01 ,  2.   , ...,  0.   ,  1.   ,  1.   ],
       ...,
       [80.   ,  1.02 ,  0.   , ...,  0.   ,  0.   ,  0.   ],
       [60.   ,  1.025,  0.   , ...,  0.   ,  0.   ,  0.   ],
       [80.   ,  1.025,  0.   , ...,  0.   ,  0.   ,  0.   ]])

In [39]:
y

array([[0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
    

In [40]:
from sklearn.model_selection import train_test_split

In [41]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=0)

In [42]:
x_train

array([[60.   ,  1.02 ,  0.   , ...,  0.   ,  0.   ,  0.   ],
       [80.   ,  1.01 ,  0.   , ...,  0.   ,  0.   ,  0.   ],
       [80.   ,  1.005,  3.   , ...,  0.   ,  0.   ,  0.   ],
       ...,
       [70.   ,  1.02 ,  0.   , ...,  0.   ,  0.   ,  0.   ],
       [80.   ,  1.01 ,  3.   , ...,  0.   ,  0.   ,  0.   ],
       [80.   ,  1.01 ,  1.   , ...,  0.   ,  0.   ,  0.   ]])

In [43]:
from sklearn.linear_model import LogisticRegression

In [44]:
lr=LogisticRegression()

In [45]:
lr.fit(x_train,y_train)

C:\Users\Gokul\anaconda3\lib\site-packages\sklearn\utils\validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Gokul\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=None, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [57]:
import pickle
pickle.dump(lr,open('decison2.pkl','wb'))

In [47]:
y_pred=lr.predict(x_test)

In [48]:
y_test

array([[0],
       [2],
       [2],
       [0],
       [0],
       [0],
       [0],
       [2],
       [0],
       [0],
       [1],
       [0],
       [0],
       [2],
       [0],
       [0],
       [2],
       [0],
       [0],
       [0],
       [0],
       [2],
       [0],
       [2],
       [0],
       [2],
       [0],
       [0],
       [2],
       [0],
       [0],
       [2],
       [2],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [2],
       [0],
       [2],
       [0],
       [0],
       [2],
       [0],
       [2],
       [2],
       [0],
       [0],
       [0],
       [0],
       [2],
       [0],
       [2],
       [2],
       [0],
       [0],
       [0],
       [0],
       [0],
       [2],
       [0],
       [2],
       [0],
       [2],
       [0],
       [0],
       [0],
       [2],
       [0],
       [2],
       [0],
       [0],
       [0],
       [0],
       [2],
       [2],
       [2],
       [2]])

In [49]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred)

0.925

In [50]:
y_test

array([[0],
       [2],
       [2],
       [0],
       [0],
       [0],
       [0],
       [2],
       [0],
       [0],
       [1],
       [0],
       [0],
       [2],
       [0],
       [0],
       [2],
       [0],
       [0],
       [0],
       [0],
       [2],
       [0],
       [2],
       [0],
       [2],
       [0],
       [0],
       [2],
       [0],
       [0],
       [2],
       [2],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [2],
       [0],
       [2],
       [0],
       [0],
       [2],
       [0],
       [2],
       [2],
       [0],
       [0],
       [0],
       [0],
       [2],
       [0],
       [2],
       [2],
       [0],
       [0],
       [0],
       [0],
       [0],
       [2],
       [0],
       [2],
       [0],
       [2],
       [0],
       [0],
       [0],
       [2],
       [0],
       [2],
       [0],
       [0],
       [0],
       [0],
       [2],
       [2],
       [2],
       [2]])

In [51]:
y_pred

array([0, 2, 2, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 2, 0, 0, 2, 0, 0, 0, 0, 2,
       0, 2, 0, 2, 0, 0, 2, 2, 0, 2, 2, 0, 0, 0, 0, 2, 0, 2, 0, 2, 2, 0,
       2, 0, 2, 2, 0, 0, 0, 0, 2, 0, 0, 2, 0, 0, 0, 0, 0, 2, 0, 2, 0, 2,
       0, 0, 0, 2, 0, 2, 0, 0, 0, 0, 2, 0, 2, 2])

In [56]:
print(lr.predict([[76.45,1.017,1.014,0,0,210,176,136,8.4,1,0,1]]))

[0]


In [53]:
print(lr.predict([[80,1.025,0,0,0,125,17,140,15.7,0,0,0]]))

[2]


In [54]:
x_test

array([[ 76.46907216,   1.01740793,   1.01694915,   0.        ,
          0.        , 219.        , 176.        , 136.        ,
          8.6       ,   1.        ,   0.        ,   1.        ],
       [ 60.        ,   1.02      ,   0.        ,   0.        ,
          0.        , 129.        ,  25.        , 139.        ,
         17.2       ,   0.        ,   0.        ,   0.        ],
       [ 70.        ,   1.025     ,   0.        ,   0.        ,
          0.        , 130.        ,  37.        , 150.        ,
         13.4       ,   0.        ,   0.        ,   0.        ],
       [100.        ,   1.01      ,   3.        ,   0.        ,
          0.        , 129.        , 158.        , 122.        ,
          8.1       ,   1.        ,   1.        ,   1.        ],
       [110.        ,   1.015     ,   3.        ,   1.        ,
          0.        , 106.        , 215.        , 120.        ,
          8.6       ,   1.        ,   0.        ,   1.        ],
       [ 90.        ,   1.02      ,

In [55]:
y_pred

array([0, 2, 2, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 2, 0, 0, 2, 0, 0, 0, 0, 2,
       0, 2, 0, 2, 0, 0, 2, 2, 0, 2, 2, 0, 0, 0, 0, 2, 0, 2, 0, 2, 2, 0,
       2, 0, 2, 2, 0, 0, 0, 0, 2, 0, 0, 2, 0, 0, 0, 0, 0, 2, 0, 2, 0, 2,
       0, 0, 0, 2, 0, 2, 0, 0, 0, 0, 2, 0, 2, 2])