In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [3]:
start =pd.read_csv('kidney_disease.csv')
start=start.iloc[:,1:]
start.drop('wc',axis=1,inplace=True)
start.drop('pcv',axis=1,inplace=True)
start.drop('rc',axis=1,inplace=True)
start

age    bp     sg   al   su     rbc        pc         pcc          ba  \
0    48.0  80.0  1.020  1.0  0.0     NaN    normal  notpresent  notpresent   
1     7.0  50.0  1.020  4.0  0.0     NaN    normal  notpresent  notpresent   
2    62.0  80.0  1.010  2.0  3.0  normal    normal  notpresent  notpresent   
3    48.0  70.0  1.005  4.0  0.0  normal  abnormal     present  notpresent   
4    51.0  80.0  1.010  2.0  0.0  normal    normal  notpresent  notpresent   
..    ...   ...    ...  ...  ...     ...       ...         ...         ...   
395  55.0  80.0  1.020  0.0  0.0  normal    normal  notpresent  notpresent   
396  42.0  70.0  1.025  0.0  0.0  normal    normal  notpresent  notpresent   
397  12.0  80.0  1.020  0.0  0.0  normal    normal  notpresent  notpresent   
398  17.0  60.0  1.025  0.0  0.0  normal    normal  notpresent  notpresent   
399  58.0  80.0  1.025  0.0  0.0  normal    normal  notpresent  notpresent   

       bgr  ...    sod  pot  hemo  htn   dm cad appet   pe  ane classification  
0    121.0  ...    NaN  NaN  15.4  yes  yes  no  good   no   no            ckd  
1      NaN  ...    NaN  NaN  11.3   no   no  no  good   no   no            ckd  
2    423.0  ...    NaN  NaN   9.6   no  yes  no  poor   no  yes            ckd  
3    117.0  ...  111.0  2.5  11.2  yes   no  no  poor  yes  yes            ckd  
4    106.0  ...    NaN  NaN  11.6   no   no  no  good   no   no            ckd  
..     ...  ...    ...  ...   ...  ...  ...  ..   ...  ...  ...            ...  
395  140.0  ...  150.0  4.9  15.7   no   no  no  good   no   no         notckd  
396   75.0  ...  141.0  3.5  16.5   no   no  no  good   no   no         notckd  
397  100.0  ...  137.0  4.4  15.8   no   no  no  good   no   no         notckd  
398  114.0  ...  135.0  4.9  14.2   no   no  no  good   no   no         notckd  
399  131.0  ...  141.0  3.5  15.8   no   no  no  good   no   no         notckd  

[400 rows x 22 columns]

In [4]:
start.isnull().any()

age                True
bp                 True
sg                 True
al                 True
su                 True
rbc                True
pc                 True
pcc                True
ba                 True
bgr                True
bu                 True
sc                 True
sod                True
pot                True
hemo               True
htn                True
dm                 True
cad                True
appet              True
pe                 True
ane                True
classification    False
dtype: bool

In [5]:
start['age'].fillna((start['age'].mean()),inplace=True)

In [6]:
start.isnull().any()

age               False
bp                 True
sg                 True
al                 True
su                 True
rbc                True
pc                 True
pcc                True
ba                 True
bgr                True
bu                 True
sc                 True
sod                True
pot                True
hemo               True
htn                True
dm                 True
cad                True
appet              True
pe                 True
ane                True
classification    False
dtype: bool

In [7]:
start['bp'].fillna((start['bp'].mean()),inplace=True)
start['sg'].fillna((start['sg'].mean()),inplace=True)
start['al'].fillna((start['al'].mean()),inplace=True)
start['su'].fillna((start['su'].mean()),inplace=True)
start['bgr'].fillna((start['bgr'].mean()),inplace=True)
start['bu'].fillna((start['bu'].mean()),inplace=True)
start['sc'].fillna((start['sc'].mean()),inplace=True)
start['sod'].fillna((start['sod'].mean()),inplace=True)
start['pot'].fillna((start['pot'].mean()),inplace=True)
start['hemo'].fillna((start['hemo'].mean()),inplace=True)

In [8]:
start['rbc']=start['rbc'].fillna(value=start['rbc'].mode().iloc[0])
start['dm']=start['dm'].fillna(value=start['dm'].mode().iloc[0])
start['htn']=start['htn'].fillna(value=start['htn'].mode().iloc[0])
start['ba']=start['ba'].fillna(value=start['ba'].mode().iloc[0])
start['pcc']=start['pcc'].fillna(value=start['pcc'].mode().iloc[0])
start['pc']=start['pc'].fillna(value=start['pc'].mode().iloc[0])
start['cad']=start['cad'].fillna(value=start['cad'].mode().iloc[0])
start['appet']=start['appet'].fillna(value=start['appet'].mode().iloc[0])
start['pe']=start['pe'].fillna(value=start['pe'].mode().iloc[0])
start['ane']=start['ane'].fillna(value=start['ane'].mode().iloc[0])

In [9]:
start.isnull().any()

age               False
bp                False
sg                False
al                False
su                False
rbc               False
pc                False
pcc               False
ba                False
bgr               False
bu                False
sc                False
sod               False
pot               False
hemo              False
htn               False
dm                False
cad               False
appet             False
pe                False
ane               False
classification    False
dtype: bool

In [10]:
from sklearn.preprocessing import LabelEncoder
lb=LabelEncoder()
start['rbc']=lb.fit_transform(start['rbc'])
start['rbc']

0      1
1      1
2      1
3      1
4      1
      ..
395    1
396    1
397    1
398    1
399    1
Name: rbc, Length: 400, dtype: int32

In [11]:
start['pc']=lb.fit_transform(start['pc'])
start['pcc']=lb.fit_transform(start['pcc'])
start['ba']=lb.fit_transform(start['ba'])
start['htn']=lb.fit_transform(start['htn'])
start['dm']=lb.fit_transform(start['dm'])
start['cad']=lb.fit_transform(start['cad'])
start['appet']=lb.fit_transform(start['appet'])
start['pe']=lb.fit_transform(start['pe'])
start['ane']=lb.fit_transform(start['ane'])
start['classification']=lb.fit_transform(start['classification'])

In [12]:
start

age    bp     sg   al   su  rbc  pc  pcc  ba         bgr  ...  \
0    48.0  80.0  1.020  1.0  0.0    1   1    0   0  121.000000  ...   
1     7.0  50.0  1.020  4.0  0.0    1   1    0   0  148.036517  ...   
2    62.0  80.0  1.010  2.0  3.0    1   1    0   0  423.000000  ...   
3    48.0  70.0  1.005  4.0  0.0    1   0    1   0  117.000000  ...   
4    51.0  80.0  1.010  2.0  0.0    1   1    0   0  106.000000  ...   
..    ...   ...    ...  ...  ...  ...  ..  ...  ..         ...  ...   
395  55.0  80.0  1.020  0.0  0.0    1   1    0   0  140.000000  ...   
396  42.0  70.0  1.025  0.0  0.0    1   1    0   0   75.000000  ...   
397  12.0  80.0  1.020  0.0  0.0    1   1    0   0  100.000000  ...   
398  17.0  60.0  1.025  0.0  0.0    1   1    0   0  114.000000  ...   
399  58.0  80.0  1.025  0.0  0.0    1   1    0   0  131.000000  ...   

            sod       pot  hemo  htn  dm  cad  appet  pe  ane  classification  
0    137.528754  4.627244  15.4    1   4    1      0   0    0               0  
1    137.528754  4.627244  11.3    0   3    1      0   0    0               0  
2    137.528754  4.627244   9.6    0   4    1      1   0    1               0  
3    111.000000  2.500000  11.2    1   3    1      1   1    1               0  
4    137.528754  4.627244  11.6    0   3    1      0   0    0               0  
..          ...       ...   ...  ...  ..  ...    ...  ..  ...             ...  
395  150.000000  4.900000  15.7    0   3    1      0   0    0               2  
396  141.000000  3.500000  16.5    0   3    1      0   0    0               2  
397  137.000000  4.400000  15.8    0   3    1      0   0    0               2  
398  135.000000  4.900000  14.2    0   3    1      0   0    0               2  
399  141.000000  3.500000  15.8    0   3    1      0   0    0               2  

[400 rows x 22 columns]

In [13]:
x=start.iloc[:,0:21].values
y=start.iloc[:,21:].values
x

array([[48.   , 80.   ,  1.02 , ...,  0.   ,  0.   ,  0.   ],
       [ 7.   , 50.   ,  1.02 , ...,  0.   ,  0.   ,  0.   ],
       [62.   , 80.   ,  1.01 , ...,  1.   ,  0.   ,  1.   ],
       ...,
       [12.   , 80.   ,  1.02 , ...,  0.   ,  0.   ,  0.   ],
       [17.   , 60.   ,  1.025, ...,  0.   ,  0.   ,  0.   ],
       [58.   , 80.   ,  1.025, ...,  0.   ,  0.   ,  0.   ]])

In [14]:
y

array([[0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
    

In [15]:
from sklearn.model_selection import train_test_split

In [16]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=0)

In [17]:
x_train

array([[25.        , 60.        ,  1.02      , ...,  0.        ,
         0.        ,  0.        ],
       [55.        , 80.        ,  1.01      , ...,  0.        ,
         0.        ,  0.        ],
       [35.        , 80.        ,  1.005     , ...,  0.        ,
         1.        ,  0.        ],
       ...,
       [51.48337596, 70.        ,  1.02      , ...,  0.        ,
         0.        ,  0.        ],
       [11.        , 80.        ,  1.01      , ...,  0.        ,
         0.        ,  0.        ],
       [62.        , 80.        ,  1.01      , ...,  0.        ,
         0.        ,  0.        ]])

In [18]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.preprocessing import StandardScaler
from sklearn import neighbors

In [19]:
clf=neighbors.KNeighborsClassifier()
clf.fit(x_train,y_train)

C:\Users\Gokul\anaconda3\lib\site-packages\ipykernel_launcher.py:2: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  


KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=5, p=2,
                     weights='uniform')

In [20]:
y_pred=clf.predict(x_test)

In [21]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred)

0.8375

In [1]:
import statsmodels.api as sm

In [22]:
x

array([[48.   , 80.   ,  1.02 , ...,  0.   ,  0.   ,  0.   ],
       [ 7.   , 50.   ,  1.02 , ...,  0.   ,  0.   ,  0.   ],
       [62.   , 80.   ,  1.01 , ...,  1.   ,  0.   ,  1.   ],
       ...,
       [12.   , 80.   ,  1.02 , ...,  0.   ,  0.   ,  0.   ],
       [17.   , 60.   ,  1.025, ...,  0.   ,  0.   ,  0.   ],
       [58.   , 80.   ,  1.025, ...,  0.   ,  0.   ,  0.   ]])

In [25]:
x=np.append(arr=np.ones((400,1)).astype(int),values=x,axis=1)
x

array([[ 1., 48., 80., ...,  0.,  0.,  0.],
       [ 1.,  7., 50., ...,  0.,  0.,  0.],
       [ 1., 62., 80., ...,  1.,  0.,  1.],
       ...,
       [ 1., 12., 80., ...,  0.,  0.,  0.],
       [ 1., 17., 60., ...,  0.,  0.,  0.],
       [ 1., 58., 80., ...,  0.,  0.,  0.]])

In [31]:
x_opt=np.array(x[:,[0,1,2,3,4,5,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21]],dtype=float)
regressor_ols=sm.OLS(endog=y,exog=x_opt).fit()
regressor_ols.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                      y   R-squared:                       0.733
Model:                            OLS   Adj. R-squared:                  0.719
Method:                 Least Squares   F-statistic:                     51.94
Date:                Fri, 14 Aug 2020   Prob (F-statistic):           1.81e-95
Time:                        15:51:45   Log-Likelihood:                -290.28
No. Observations:                 400   AIC:                             622.6
Df Residuals:                     379   BIC:                             706.4
Df Model:                          20                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const        -64.8477      6.171    -10.508      0.000     -76.982     -52.713
x1            -0.0002      0.002     -0.102      0.918      -0.004       0.003
x2            -0.0046      0.002     -2.243      0.026      -0.009      -0.001
x3            62.6179      6.130     10.216      0.000      50.566      74.670
x4            -0.1281      0.030     -4.245      0.000      -0.187      -0.069
x5            -0.0343      0.035     -0.970      0.332      -0.104       0.035
x6            -0.0828      0.090     -0.916      0.360      -0.261       0.095
x7             0.0892      0.105      0.852      0.395      -0.117       0.295
x8             0.1617      0.127      1.276      0.203      -0.087       0.411
x9            -0.0008      0.000     -1.677      0.094      -0.002       0.000
x10            0.0014      0.001      1.790      0.074      -0.000       0.003
x11           -0.0026      0.007     -0.360      0.719      -0.017       0.011
x12            0.0059      0.004      1.507      0.133      -0.002       0.014
x13           -0.0042      0.010     -0.411      0.681      -0.025       0.016
x14            0.1405      0.016      8.748      0.000       0.109       0.172
x15           -0.2387      0.079     -3.030      0.003      -0.394      -0.084
x16           -0.0143      0.057     -0.252      0.802      -0.126       0.097
x17            0.0894      0.099      0.901      0.368      -0.106       0.285
x18           -0.1444      0.075     -1.917      0.056      -0.293       0.004
x19           -0.0596      0.083     -0.722      0.471      -0.222       0.103
x20            0.1994      0.091      2.192      0.029       0.021       0.378
==============================================================================
Omnibus:                       15.686   Durbin-Watson:                   1.383
Prob(Omnibus):                  0.000   Jarque-Bera (JB):               10.845
Skew:                          -0.281   Prob(JB):                      0.00442
Kurtosis:                       2.421   Cond. No.                     7.98e+04
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 7.98e+04. This might indicate that there are
strong multicollinearity or other numerical problems.
"""

In [66]:
x_opt=np.array(x[:,[0,2,3,4,8,9,10,11,13,15,16,19,21]],dtype=float)
regressor_ols=sm.OLS(endog=y,exog=x_opt).fit()
regressor_ols.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                      y   R-squared:                       0.730
Model:                            OLS   Adj. R-squared:                  0.722
Method:                 Least Squares   F-statistic:                     87.24
Date:                Fri, 14 Aug 2020   Prob (F-statistic):          4.45e-102
Time:                        17:01:30   Log-Likelihood:                -292.19
No. Observations:                 400   AIC:                             610.4
Df Residuals:                     387   BIC:                             662.3
Df Model:                          12                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const        -66.2400      6.044    -10.959      0.000     -78.124     -54.356
x1            -0.0048      0.002     -2.380      0.018      -0.009      -0.001
x2            63.9872      5.988     10.686      0.000      52.214      75.760
x3            -0.1277      0.028     -4.542      0.000      -0.183      -0.072
x4             0.1436      0.093      1.541      0.124      -0.040       0.327
x5             0.1888      0.124      1.524      0.128      -0.055       0.432
x6            -0.0010      0.000     -2.722      0.007      -0.002      -0.000
x7             0.0012      0.001      1.779      0.076      -0.000       0.002
x8             0.0060      0.003      1.971      0.049    1.36e-05       0.012
x9             0.1377      0.016      8.836      0.000       0.107       0.168
x10           -0.2486      0.071     -3.494      0.001      -0.389      -0.109
x11           -0.1483      0.071     -2.104      0.036      -0.287      -0.010
x12            0.2019      0.089      2.270      0.024       0.027       0.377
==============================================================================
Omnibus:                       15.893   Durbin-Watson:                   1.372
Prob(Omnibus):                  0.000   Jarque-Bera (JB):               11.685
Skew:                          -0.310   Prob(JB):                      0.00290
Kurtosis:                       2.438   Cond. No.                     7.67e+04
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 7.67e+04. This might indicate that there are
strong multicollinearity or other numerical problems.
"""

In [67]:
x

array([[ 1., 48., 80., ...,  0.,  0.,  0.],
       [ 1.,  7., 50., ...,  0.,  0.,  0.],
       [ 1., 62., 80., ...,  1.,  0.,  1.],
       ...,
       [ 1., 12., 80., ...,  0.,  0.,  0.],
       [ 1., 17., 60., ...,  0.,  0.,  0.],
       [ 1., 58., 80., ...,  0.,  0.,  0.]])

In [68]:
x=x[:,1:]

In [69]:
x

array([[48.   , 80.   ,  1.02 , ...,  0.   ,  0.   ,  0.   ],
       [ 7.   , 50.   ,  1.02 , ...,  0.   ,  0.   ,  0.   ],
       [62.   , 80.   ,  1.01 , ...,  1.   ,  0.   ,  1.   ],
       ...,
       [12.   , 80.   ,  1.02 , ...,  0.   ,  0.   ,  0.   ],
       [17.   , 60.   ,  1.025, ...,  0.   ,  0.   ,  0.   ],
       [58.   , 80.   ,  1.025, ...,  0.   ,  0.   ,  0.   ]])

In [76]:
start.drop('rc',axis=1,inplace=True)

age    bp     sg   al   su  rbc  pc  pcc  ba         bgr  ...  \
0    48.0  80.0  1.020  1.0  0.0    1   1    0   0  121.000000  ...   
1     7.0  50.0  1.020  4.0  0.0    1   1    0   0  148.036517  ...   
2    62.0  80.0  1.010  2.0  3.0    1   1    0   0  423.000000  ...   
3    48.0  70.0  1.005  4.0  0.0    1   0    1   0  117.000000  ...   
4    51.0  80.0  1.010  2.0  0.0    1   1    0   0  106.000000  ...   
..    ...   ...    ...  ...  ...  ...  ..  ...  ..         ...  ...   
395  55.0  80.0  1.020  0.0  0.0    1   1    0   0  140.000000  ...   
396  42.0  70.0  1.025  0.0  0.0    1   1    0   0   75.000000  ...   
397  12.0  80.0  1.020  0.0  0.0    1   1    0   0  100.000000  ...   
398  17.0  60.0  1.025  0.0  0.0    1   1    0   0  114.000000  ...   
399  58.0  80.0  1.025  0.0  0.0    1   1    0   0  131.000000  ...   

            sod       pot  hemo  htn  dm  cad  appet  pe  ane  classification  
0    137.528754  4.627244  15.4    1   4    1      0   0    0               0  
1    137.528754  4.627244  11.3    0   3    1      0   0    0               0  
2    137.528754  4.627244   9.6    0   4    1      1   0    1               0  
3    111.000000  2.500000  11.2    1   3    1      1   1    1               0  
4    137.528754  4.627244  11.6    0   3    1      0   0    0               0  
..          ...       ...   ...  ...  ..  ...    ...  ..  ...             ...  
395  150.000000  4.900000  15.7    0   3    1      0   0    0               2  
396  141.000000  3.500000  16.5    0   3    1      0   0    0               2  
397  137.000000  4.400000  15.8    0   3    1      0   0    0               2  
398  135.000000  4.900000  14.2    0   3    1      0   0    0               2  
399  141.000000  3.500000  15.8    0   3    1      0   0    0               2  

[400 rows x 22 columns]

In [ ]:
start.drop('rc',axis=1,inplace=True)